[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "abacusIsaacPrecieux"
version = "0.1.0"
description = "comprehensive calculator for various mathematical operations"
readme = "README.md"
authors = [
    { name = "N.I Precieux", email = "niyobyoseisaac@rca.ac.rw" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.8"
dependencies = []

[project.urls]
Homepage = "https://github.com/Isaac-1-lang/__a__b__a__c__u__s__"
